# -*- coding: utf-8 -*-
"""DecisionTreeRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pGvWU1GULeZmS80KHdjRVccSXWIHnjn5

**Importing the libraries**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""**Importing the dataset**"""

data=pd.read_csv("Position_Salaries.csv")
x=data.iloc[:,1:2].values
y=data.iloc[:,-1].values
print(x)
print(y)

y=y.reshape(len(y),1 )

"""**Fitting Decision Tree Regression on dataset**"""

from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor(random_state=0)
regressor.fit(x, y)

"""**Predicting the new result**"""

regressor.predict([[7.5]])

y_pred=regressor.predict(x)
print(y_pred)

"""**Splitting the train/ test set**"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2, random_state=0)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

"""**Feature Scaling**"""

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

print(x_train)
print(x_test)

"""**Visualising the result**"""

plt.scatter(x,y, color='red')
plt.plot(x,regressor.predict(x), color='blue')
plt.title("Salary vs Years of Experience")
plt.xlabel('Years of experience')
plt.ylabel('Salary')
plt.show()